subscription routineUpdated {
  routineUpdated {
    id
    text
    description
    parents {
      id
      text
    }
    children {
      id
      text
    }
    metrics {
      id
      text
    }
    goals {
      id
      text
    }
    todos {
      id
      text
    }
  }
}
