subscription metricUpdated {
  metricUpdated {
    id
    text
    description
    goals {
      id
      text
      position
    }
    todos {
      id
      text
      position
    }
    routines {
      id
      text
      position
    }
  }
}
