query events {
    events {
      id
      text
      startAt
      endAt
      isAllDay
      isRecommended
      type {
        id
        text
      }
      iterations {
        id
        text
        startAt
        endAt
        attemptedAt
        completedAt
        routineIteration {
          id
          todoIterations {
            id
            text
            startAt
            endAt
            attemptedAt
            completedAt
          }
        }
      }
    }
}