query iterations($type: String, $start: String, $end: String, ) {
    iterations(type: $type, start: $start, end: $end) {
        id
        text
        startAt
        endAt
        attemptedAt
        completedAt
        isRecommended
        todo {
            id
            text
            metrics {
                id
                text
            }
            goals {
                id
                text
            }
            routines {
                id
                text
            }
        }
        routineIteration {
            id
            todoIterations {
                id
                text
                startAt
                endAt
                attemptedAt
                completedAt
            }
            idRoutineIteration
        }
        idRoutineIteration
    }
}