query eventsAndIterations {
  eventsAndIterations {
    events {
      id
      text
      startAt
      endAt
      isAllDay
      isRecommended
      type {
        id
        text
      }
      iterations {
        id
        text
        startAt
        endAt
        attemptedAt
        completedAt
        todo {
            id
            text
            metrics {
                id
                text
            }
            goals {
                id
                text
            }
            routines {
                id
                text
            }
        }
        routineIteration {
          id
          todoIterations {
            id
            text
            startAt
            endAt
            attemptedAt
            completedAt
            events {
              id
              startAt
              endAt
            }
          }
          idRoutineIteration
        }
        events {
          id
          startAt
          endAt
        }
        idRoutineIteration
      }
    }
    iterations {
        id
        text
        startAt
        endAt
        attemptedAt
        completedAt
        isRecommended
        todo {
          id
          text
          metrics {
              id
              text
          }
          goals {
              id
              text
          }
          routines {
              id
              text
          }
        }
        routineIteration {
          id
          todoIterations {
            id
            text
            startAt
            endAt
            attemptedAt
            completedAt
            events {
              id
              startAt
              endAt
            }
          }
          idRoutineIteration
        }
        idRoutineIteration
        events {
            id
            startAt
            endAt
        }
      }
  }
}