subscription iterationAdded {
  iterationAdded {
    id
    text
    startAt
    endAt
    attemptedAt
    completedAt
    isRecommended
    todos {
      id
      text
      metrics {
        id
        text
      }
    }
    todoRepeat {
      id
    }
  }
}
