subscription iterationUpdated {
  iterationUpdated {
    id
    text
    startAt
    endAt
    attemptedAt
    completedAt
    isRecommended
    todo {
        id
        text
        metrics {
            id
            text
        }
        goals {
            id
            text
        }
        routines {
            id
            text
        }
    }
    routineIteration {
      id
      todoIterations {
        id
        text
        startAt
        endAt
        attemptedAt
        completedAt
      }
      idRoutineIteration
    }
    todoRepeat {
      id
    }
    idRoutineIteration
    events {
        id
    }
  }
}
