subscription todoUpdated {
  todoUpdated {
    id
    text
    description
    isGroup
    parents {
      id
      text
    }
    children {
      id
      text
    }
    metrics {
      id
      text
    }
    goals {
      id
      text
    }
    routines {
      id
      text
    }
    timePairs {
      id
      timeType {
        id
        text
      }
      startTime {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      endTime {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
    }
    repeats {
      id
      type {
        id
        text
      }
      timeframe {
        id
        text
      }
      startRepeat {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      endRepeat {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      startIteration {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      endIteration {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      interval
      frequency
      dayIndecies {
        id
        index
      }
      routines { 
        id
      }
      routine_repeats {
        id
        lastIterationDateTime
        isEventVisible
        routine {
          id
          text
        }
      }
    }
    iterations {
      id
      text
      startAt
      endAt
      attemptedAt
      completedAt
      isRecommended
    }
  }
}
