query items($getMetrics: Boolean, $getGoals: Boolean, $getTodos: Boolean, $getRoutines: Boolean) {
    items(getMetrics: $getMetrics, getGoals: $getGoals, getTodos: $getTodos, getRoutines: $getRoutines) {
        metrics {
            id
            text
            description
            goals {
                id
                text
            }
            todos {
                id
                text
            }
            routines {
                id
                text
            }
        }
        goals {
            id
            text
            description
            parents {
                id
                text
            }
            children {
                id
                text
            }
            metrics {
                id
                text
            }
            todos {
                id
                text
            }
            routines {
                id
                text
            }
            timePairs {
                id
                timeType {
                id
                text
                }
                startTime {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                endTime {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
            }
            repeats {
                id
                type {
                id
                text
                }
                timeframe {
                id
                text
                }
                startRepeat {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                endRepeat {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                startIteration {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                endIteration {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                interval
                frequency
                dayIndecies {
                id
                index
                }
            }
        }
        todos {
            id
            text
            description
            isGroup
            parents {
                id
                text
            }
            children {
                id
                text
            }
            metrics {
                id
                text
            }
            goals {
                id
                text
            }
            routines {
                id
                text
            }
            timePairs {
                id
                timeType {
                id
                text
                }
                startTime {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                endTime {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
            }
            repeats {
                id
                type {
                id
                text
                }
                timeframe {
                    id
                    text
                }
                startRepeat {
                    id
                    type {
                        id
                        text
                    }
                    endpoint {
                        id
                        text
                    }
                    moment {
                        id
                        text
                    }
                    flexibility {
                        id
                        text
                    }
                    dateTime
                }
                endRepeat {
                    id
                    type {
                        id
                        text
                    }
                    endpoint {
                        id
                        text
                    }
                    moment {
                        id
                        text
                    }
                    flexibility {
                        id
                        text
                    }
                    dateTime
                }
                startIteration {
                    id
                    type {
                        id
                        text
                    }
                    endpoint {
                        id
                        text
                    }
                    moment {
                        id
                        text
                    }
                    flexibility {
                        id
                        text
                    }
                    dateTime
                }
                endIteration {
                    id
                    type {
                        id
                        text
                    }
                    endpoint {
                        id
                        text
                    }
                    moment {
                        id
                        text
                    }
                    flexibility {
                        id
                        text
                    }
                    dateTime
                }
                interval
                frequency
                dayIndecies {
                    id
                    index
                }
                routines { 
                    id
                }
                routine_repeats {
                    id
                    lastIterationDateTime
                    isEventVisible
                    routine {
                        id
                        text
                    }
                }
                todo_repeats {
                    id
                    lastIterationDateTime
                    isEventVisible
                }
            }
            iterations {
                id
                text
                startAt
                endAt
                attemptedAt
                completedAt
                isRecommended
            }
        }
        routines {
            id
            text
            description
            parents {
                id
                text
            }
            children {
                id
                text
            }
            metrics {
                id
                text
            }
            goals {
                id
                text
            }
            todos {
                id
                text
            }
            timePairs {
                id
                timeType {
                id
                text
                }
                startTime {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                endTime {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
            }
            repeats {
                id
                type {
                id
                text
                }
                timeframe {
                id
                text
                }
                startRepeat {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                endRepeat {
                id
                type {
                    id
                    text
                }
                endpoint {
                    id
                    text
                }
                moment {
                    id
                    text
                }
                flexibility {
                    id
                    text
                }
                dateTime
                }
                startIteration {
                    id
                    type {
                        id
                        text
                    }
                    endpoint {
                        id
                        text
                    }
                    moment {
                        id
                        text
                    }
                    flexibility {
                        id
                        text
                    }
                    dateTime
                }
                endIteration {
                    id
                    type {
                        id
                        text
                    }
                    endpoint {
                        id
                        text
                    }
                    moment {
                        id
                        text
                    }
                    flexibility {
                        id
                        text
                    }
                    dateTime    
                }
                interval
                frequency
                dayIndecies {
                    id
                    index
                }
            }
        }
    }
}