query routines {
  routines {
    id
    text
    description
    position
    parents {
      id
      text
      position
    }
    children {
      id
      text
      position
    }
    metrics {
      id
      text
    }
    goals {
      id
      text
      position
    }
    todos {
      id
      text
      position
      repeats {
        id
        type {
          id
          text
        }
        timeframe {
          id
          text
        }
        startRepeat {
          id
          type {
            id
            text
          }
          endpoint {
            id
            text
          }
          moment {
            id
            text
          }
          flexibility {
            id
            text
          }
          dateTime
        }
        endRepeat {
          id
          type {
            id
            text
          }
          endpoint {
            id
            text
          }
          moment {
            id
            text
          }
          flexibility {
            id
            text
          }
          dateTime
        }
        startIteration {
          id
          type {
            id
            text
          }
          endpoint {
            id
            text
          }
          moment {
            id
            text
          }
          flexibility {
            id
            text
          }
          dateTime
        }
        endIteration {
          id
          type {
            id
            text
          }
          endpoint {
            id
            text
          }
          moment {
            id
            text
          }
          flexibility {
            id
            text
          }
          dateTime
        }
        interval
        frequency
        dayIndecies {
          id
          index
        }
        routineRepeat {
          id
        }
      }
    }
    timePairs {
      id
      timeType {
        id
        text
      }
      startTime {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      endTime {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
    }
    repeats {
      id
      type {
        id
        text
      }
      timeframe {
        id
        text
      }
      startRepeat {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      endRepeat {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      startIteration {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      endIteration {
        id
        type {
          id
          text
        }
        endpoint {
          id
          text
        }
        moment {
          id
          text
        }
        flexibility {
          id
          text
        }
        dateTime
      }
      interval
      frequency
      dayIndecies {
        id
        index
      }
    }
  }
}
