query routineIterations {
  routineIterations {
    id
    idRoutineIteration
    hasTodoEvent
    routineIteration {
      id
      text
      startAt
      endAt
      attemptedAt
      completedAt
      isRecommended
    }
    todoIterations {
      id
      text
      startAt
      endAt
      todo {
        id
        text
      }
      attemptedAt
      completedAt
      isRecommended
    }
  }
}
