export let METRIC = {
    PHYSICAL: 1,
    SOCIAL: 2,
    MENTAL: 3,
    EMOTIONAL: 4,
    FINANCIAL: 5
};

export let TODOTYPE = {
    REMINDER: 9,
    TALLY: 10,
    INVERSE: 11,
    ERRAND: 12,
    MEMORIZATION: 190
};

export let ROUTINETYPES = {
    TASKROUTINE: 13,
    LIFESTYLE: 14,
    MAINTAINANCE: 15,
    HOUSEKEEPING: 16
};

export let TIMEFRAME = {
    MILLISECOND: 39,
    SECOND: 40,
    MINUTE: 41,
    HOUR: 42,
    DAY: 43,
    WORKDAY: 44,
    WEEKDAY: 45,
    WEEKENDDAY: 46,
    WEEKEND: 47,
    WEEK: 48,
    MONTH: 49,
    SEASON: 50,
    QUARTER: 51,
    TRIMESTER: 52,
    BIMESTER: 53,
    SEMESTER: 54,
    YEAR: 55,
    MILESTONE: 56,
    LIFE: 57
};

export let REPETITION = {
    MILLISECONDLY: 59,
    SECONDLY: 60,
    MINUTELY: 61,
    HOURLY: 62,
    DAILY: 63,
    WORKDAYLY: 64,
    WEEKDAYLY: 65,
    WEEKENDDAYLY: 66,
    WEEKENDLY: 67,
    WEEKLY: 68,
    MONTHLY: 69,
    SEASONLY: 70,
    QUARTERLY: 71,
    TRIANUALLY: 72,
    BIANUALLY: 73,
    SENUANUALLY: 74,
    ANUALLY: 75
};

export let TIMETYPE = {
    SCHEDULED: 80,
    RECOMMENDED: 81,
    DUE: 82
};

export let MOMENT = {
    DATE: 87,
    TIME: 88,
    DATETIME: 89
};

export let INHERITANCE = {
    SELF: 140,
    CHILDREN: 141,
    DESCENDANTS: 142
};

export let CONTROL = {
    CONTROL: 105,
    SLIDER: 106,
    NUMBERPAD: 107,
    COUNTER: 108,
    TEXTBOX: 109,
    TEXTAREA: 110,
    TEXTBLOCK: 111,
    DROPDOWN: 112
};

export let EVENTTYPE = {
    EVENTTYPE: 122,
    EVENT: 123,
    ALLDAY: 124,
    TODO: 125,
    TASK: 126,
    ROUTINE: 127,
    ROUTINE2: 128,
    TASKROUTINE: 129,
    SUBTYPE: 130,
    SLEEP: 131,
    BRIEFING: 132,
    MEAL: 133,
    WORKOUT: 134,
    LOG: 135,
    INVENTORY: 136,
    TIME: 137,
    REPETITIVE: 138
};

export let TODO_ACTIVITY_TYPE = {
    LOG: 157,
    SLEEP: 153,
    BRIEFING: 154,
    MEAL: 155,
    WORKOUT: 156,
    EXERCISE: 158,
    WATER: 159,
};

export let BLURBTYPE = {
    ADVICE: 162,
    REASON: 163,
    MEASUREOFSUCCESS: 164,
    NOTE: 165,
    BLURB: 166,
    QUESTION: 167,
    ANSWER: 168,
    INSECURITY: 169,
    REMINDER: 170,
    BRIEFING: 172,
    DEBRIEFING: 173,
    ISSUE: 184
};

export let CALENDAR_TYPES = {
    WEEK: "week",
    MONTH: "month"
};

export let WORKOUT_SECTIONS = {
    MAIN: 150,
    WARMUP: 174,
    STRETCH: 175,
    WARMUP_STETCH: 176,
    SKILL_TRAINING: 177,
    STRENGTH: 178,
    COOL_DOWN: 179,
    MOBILITY: 180
}

export let WORKOUT_VIEWS = {
    DASHBOARD: "dashboard",
    WORKOUT_LIST: "workoutList",
    WORKOUT_ACTIVE: "workoutActive",
    WORKOUT_FORM: "workoutForm",
    EXERCISE_LIST: "exerciseList",
    EXERCISE_FORM: "exerciseForm"
}

export let GOAL_TYPE = {
    GOAL_TYPE: 182,
    FITNESS: 183,
}

export let LOG_ITEMS = {
    EMOTIONAL_MOOD: 1,
    MENTAL_ENERGY: 6,
    MENTAL_CLARITY: 7,
    PHYSICAL_ENERGY: 11,
    PHYSICAL_SLEEPINESS: 12,

}