subscription eventUpdated {
    eventUpdated {
      id
      text
      startAt
      endAt
      isAllDay
      isRecommended
      type {
        id
        text
      }
      iterations {
        id
        text
        startAt
        endAt
        attemptedAt
        completedAt
        todos {
            id
            text
            metrics {
                id
                text
            }
            goals {
                id
                text
            }
            routines {
                id
                text
            }
        }
        routineIteration {
          id
          todoIterations {
            id
            text
            startAt
            endAt
            attemptedAt
            completedAt
            events {
              id
              startAt
              endAt
            }
            idRoutineIteration
          }
        }
        events {
          id
          startAt
          endAt
        }
      }
    }
}